Added two py files for pytest
ivanbarcelos90/FinanceDataLake pull request #2
Opened 2022-01-11 21:34 UTC by ivanbarcelos90

# Description

Added py file for testing pytest in a basic math function.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

It was tested using pytest in pycharm IDE. 
The math function "pow" was used as an example for testing the passed and failed status of pytest.

- [ ] Test A : 2 by the power of 2 must equal 4. Test passed. 
- [ ] Test B: -2 by the power of 2 must equal 4. Test passed.
- [ ] Test C : 3 by the power of 3 must equal 9. Test failed.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-11 21:36 UTC, ivanbarcelos90 commented
Igor, you can review my first try at pull request.

2022-01-11 23:13 UTC, ivtavares requested changes

2022-01-11 23:13 UTC, ivtavares commented on finance_data_lake/app.py
> +
Remove the empty lines

2022-01-11 23:13 UTC, ivtavares commented on tests/test_app.py
> +    assert app.power(3, 3) == 9
Add an empty line here

2022-01-11 23:13 UTC, ivtavares commented on tests/test_app.py
> +
Please check pytest parametize

2022-01-13 12:35 UTC, ivtavares commented on finance_data_lake/app.py
> +
When you finish your modification, you should click on Resolve conversation

2022-01-13 12:35 UTC, ivtavares commented on tests/test_app.py
> +    assert app.power(3, 3) == 9
When you finish your modification, you should click on Resolve conversation

2022-01-13 12:36 UTC, ivtavares commented
We need to improve the Commit messages. "Pull request fix" does not say anything. I will search online for good patterns and send them to you

2022-01-13 12:37 UTC, ivtavares approved these changes

2022-01-13 12:37 UTC, ivtavares commented
Anyway, it is approved. You can merge

2022-01-15 10:51 UTC, merged